apiVersion: apps/v1
kind: Deployment
metadata:
  name: collect-api
  labels:
    app: collect
    role: api
    tier: backend
spec:
  selector:
    matchLabels:
      app: collect
      role: api
      tier: backend
  template:
    metadata:
      labels:
        app: collect
        role: api
        tier: backend
    spec:
      containers:
        - args:
            - python
            - main.py
          name: collect-container
          image: asia.gcr.io/collect-367002/collect-api:no-cmd-2
          env:
            - name: REDIS_HOST
              value: redis-service
            - name: REDIS_PORT
              value: "6379"
            - name: MONGO_HOST
              value: mongo-service
            - name: MONGO_PORT
              value: "27017"
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  type: LoadBalancer
  selector:
    app: collect
    role: api
    tier: backend
  ports:
    - port: 8080
      targetPort: 8080
