apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-db
  labels:
    app: mongo
    role: db
    tier: backend
spec:
  selector:
    matchLabels:
      app: mongo
      role: db
      tier: backend
  template:
    metadata:
      labels:
        app: mongo
        role: db
        tier: backend
    spec:
      containers:
        - name: mongo-db
          image: mongo:latest
          env:
            - name: MONGO_INITDB_DATABASE
              value: mongo_db
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
          ports:
            - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  labels:
    app: mongo
    role: db
    tier: backend
spec:
  selector:
    app: mongo
    role: db
    tier: backend
  ports:
    - port: 27017
      targetPort: 27017
